# Generated by Django 4.1.4 on 2023-01-06 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_remove_attendancetable_absent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendancetable',
            old_name='present',
            new_name='attendance',
        ),
        migrations.AddField(
            model_name='attendancetable',
            name='date_added',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
