# Generated by Django 4.1.4 on 2023-01-06 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_attendance_overall_remove_studentdatainfo_semester_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudentDataInfo',
            new_name='Student',
        ),
    ]
