# Generated by Django 4.1.4 on 2023-01-07 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_rename_studentdatainfo_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='attendance',
            new_name='status',
        ),
    ]
