# Generated by Django 4.1.4 on 2023-01-07 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_rename_attendance_attendance_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Attendance',
            new_name='StudentAttendances',
        ),
    ]
