# Generated by Django 4.1.4 on 2023-01-07 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0009_rename_attendance_studentattendances'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentattendances',
            old_name='status',
            new_name='absent',
        ),
        migrations.AddField(
            model_name='studentattendances',
            name='present',
            field=models.BooleanField(default=False),
        ),
    ]
