# Generated by Django 4.1.4 on 2023-01-08 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0010_rename_status_studentattendances_absent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentattendances',
            name='semester',
            field=models.CharField(blank=True, choices=[('1st', '1st'), ('2nd', '2nd')], max_length=100, null=True),
        ),
    ]
