# Generated by Django 4.1.4 on 2023-01-08 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0011_alter_studentattendances_semester'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentattendances',
            name='student',
        ),
        migrations.AddField(
            model_name='studentattendances',
            name='matric_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
