# Generated by Django 4.1.4 on 2023-01-08 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0012_remove_studentattendances_student_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentattendances',
            name='matric_no',
        ),
        migrations.AddField(
            model_name='studentattendances',
            name='student',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='attendance.student'),
            preserve_default=False,
        ),
    ]
