# Generated by Django 4.1.4 on 2023-01-12 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0013_remove_studentattendances_matric_no_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentattendances',
            name='absent',
        ),
    ]
